name: condition
on:
  issues:
    types:
      - closed
  push:
    types:
      - closed

jobs:
  state_event_type:
    runs-on: ubuntu-latest
    steps:
    - name: if_issue
      if: github.event.issue
      run: |
        echo An issue was closed
    - name: if_pr
      if: github.event.push
      run: |
        echo A pull request was closed
